export const CLUSTER_NAME_FIELD_LABEL = 'Cluster name';
export const CLUSTER_NAME_HELPER_TEXT = 'Use letters, numbers, and hyphens.';
export const CLUSTER_NAME_PLACEHOLDER_TEXT = 'Enter the cluster name';
export const API_TOKEN_FIELD_LABEL = 'API token';
export const SHOW_PASSWORD_BUTTON_NAME = 'Show password';
export const HIDE_PASSWORD_BUTTON_NAME = 'Hide password';
export const SAMPLE_CLUSTER_NAME_VALUE = 'my-cluster';
export const SECRET_PLACEHOLDER_TEXT = 'Enter the API token';
export const SAMPLE_SECRET_VALUE = 'secret123';
