import { test, expect } from '@playwright/experimental-ct-react';
import { checkAccessibility } from '../../../../../../test-helpers';
import {
  mockInstallerRoles,
  mockSupportRoles,
  mockWorkerRoles,
  mockOIDCConfig,
} from './RolesAndPoliciesSubStep.story';
import { RolesAndPoliciesSubStepMount } from './RolesAndPoliciesSubStep.spec-helpers';
import type { Resource, Role } from '../../../../types';

const mockResource = <TData,>(data: TData): Resource<TData> => ({
  data,
  error: null,
  isFetching: false,
  fetch: async () => {},
});

const mockFetchResource = <TData, TArgs extends unknown[] = []>(
  data: TData
): Resource<TData, TArgs> & { fetch: (...args: TArgs) => Promise<void> } => ({
  data,
  error: null,
  isFetching: false,
  fetch: async (..._args: TArgs) => {},
});

test.describe('RolesAndPoliciesSubStep', () => {
  test('should pass accessibility tests', async ({ mount }) => {
    const component = await mount(<RolesAndPoliciesSubStepMount />);
    await checkAccessibility({ component });
  });

  test('should render Account roles section with Installer role select', async ({ mount }) => {
    const component = await mount(<RolesAndPoliciesSubStepMount />);

    await expect(component.getByText('Account roles', { exact: true })).toBeVisible();
    await expect(component.getByText('Installer role', { exact: true })).toBeVisible();
  });

  test('should render Operator roles section with OIDC config select', async ({ mount }) => {
    const component = await mount(<RolesAndPoliciesSubStepMount />);

    await expect(component.getByText('Operator roles', { exact: true })).toBeVisible();
    await expect(component.getByText('OIDC config ID', { exact: true })).toBeVisible();
  });

  test('should render ARNs expandable section with Support and Worker role selects', async ({
    mount,
  }) => {
    const component = await mount(<RolesAndPoliciesSubStepMount />);

    const arnsToggle = component.getByRole('button', {
      name: /Amazon Resource Names \(ARNs\)/,
    });
    await expect(arnsToggle).toBeVisible();
    await arnsToggle.click();

    await expect(component.getByText('Support role', { exact: true })).toBeVisible();
    await expect(component.getByText('Worker role', { exact: true })).toBeVisible();
  });

  test('should display refresh button on Installer role', async ({ mount }) => {
    const component = await mount(<RolesAndPoliciesSubStepMount />);

    await expect(
      component
        .locator('#cluster-installer_role_arn-form-group')
        .getByLabel('Refresh', { exact: true })
    ).toBeVisible();
  });

  test('should auto-select support and worker roles when installer role is selected', async ({
    mount,
    page,
  }) => {
    const component = await mount(<RolesAndPoliciesSubStepMount />);

    const installerCombobox = component.getByRole('combobox', {
      name: 'Select an Installer role',
    });
    await installerCombobox.click();
    await page
      .getByRole('option', {
        name: /ManagedOpenShift-Installer-Role/,
      })
      .first()
      .click();

    const arnsToggle = component.getByRole('button', {
      name: /Amazon Resource Names \(ARNs\)/,
    });
    await arnsToggle.click();

    const supportCombobox = component.getByRole('combobox', {
      name: 'Select a support role',
    });
    const workerCombobox = component.getByRole('combobox', {
      name: 'Select a worker role',
    });

    await expect(supportCombobox).toHaveValue(mockSupportRoles[0].label);
    await expect(workerCombobox).toHaveValue(mockWorkerRoles[0].label);
  });

  test('should render Operator role prefix expandable section', async ({ mount }) => {
    const component = await mount(<RolesAndPoliciesSubStepMount />);

    const operatorRolesToggle = component.getByRole('button', {
      name: /Operator role prefix/,
    });
    await expect(operatorRolesToggle).toBeVisible();
  });

  test('should display Operator roles prefix input with autogenerated value', async ({ mount }) => {
    const component = await mount(
      <RolesAndPoliciesSubStepMount clusterOverrides={{ name: 'test-cluster' }} />
    );

    await expect(component.getByText('Operator roles prefix', { exact: true })).toBeVisible();
  });

  test('should display the rosa create command in clipboard copy', async ({ mount }) => {
    const component = await mount(
      <RolesAndPoliciesSubStepMount
        clusterOverrides={{
          custom_operator_roles_prefix: 'my-prefix',
          byo_oidc_config_id: 'oidc-123',
          installer_role_arn: 'arn:aws:iam::123456789012:role/Installer',
        }}
      />
    );

    const expandToggle = component.getByRole('button', { name: 'Show content' });
    await expandToggle.click();

    await expect(component.getByText(/rosa create operator-roles/)).toBeVisible();
  });

  test('should not auto-select roles when support roles list is empty', async ({ mount, page }) => {
    const component = await mount(
      <RolesAndPoliciesSubStepMount
        roles={mockFetchResource<Role[], [awsAccount: string]>([
          {
            installerRole: mockInstallerRoles[0],
            supportRole: [],
            workerRole: [],
          },
        ])}
        oidcConfig={mockResource(mockOIDCConfig)}
      />
    );

    const installerCombobox = component.getByRole('combobox', {
      name: 'Select an Installer role',
    });
    await installerCombobox.click();
    await page
      .getByRole('option', {
        name: /ManagedOpenShift-Installer-Role/,
      })
      .first()
      .click();

    const arnsToggle = component.getByRole('button', {
      name: /Amazon Resource Names \(ARNs\)/,
    });
    await arnsToggle.click();

    const supportCombobox = component.getByRole('combobox', { name: 'Select a support role' });
    await expect(supportCombobox).toHaveValue('');
  });

  test('should not auto-select roles when worker roles list is empty', async ({ mount, page }) => {
    const component = await mount(
      <RolesAndPoliciesSubStepMount
        roles={mockFetchResource<Role[], [awsAccount: string]>([
          {
            installerRole: mockInstallerRoles[0],
            supportRole: [],
            workerRole: [],
          },
        ])}
        oidcConfig={mockResource(mockOIDCConfig)}
      />
    );

    const installerCombobox = component.getByRole('combobox', {
      name: 'Select an Installer role',
    });
    await installerCombobox.click();
    await page
      .getByRole('option', {
        name: /ManagedOpenShift-Installer-Role/,
      })
      .first()
      .click();

    const arnsToggle = component.getByRole('button', {
      name: /Amazon Resource Names \(ARNs\)/,
    });
    await arnsToggle.click();

    const workerCombobox = component.getByRole('combobox', { name: 'Select a worker role' });
    await expect(workerCombobox).toHaveValue('');
  });
});
