import {
  DNS_LABEL_REGEXP,
  FIELD_NAME,
  MAX_CUSTOM_OPERATOR_ROLES_PREFIX_LENGTH,
} from '../constants';
import type { WizardFieldMeta } from './types';
import { ctx, rosaRequiredStringField } from './helpers';
import { YUP } from './constants';

export const installerRoleArnSchema = rosaRequiredStringField().meta({
  id: YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.ID,
  labelKey: YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.LABEL_KEY,
  labelHelpKey: YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.LABEL_HELP_KEY,
  placeholderKey: YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.PLACEHOLDER_KEY,
  stepId: YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.STEP_ID,
  fieldType: YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.FIELD_TYPE,
  noEditAfterSubmit: YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.NO_EDIT_AFTER_SUBMIT,
  optionsWizardDataResource:
    YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.OPTIONS_WIZARD_DATA_RESOURCE,
  refetchesResourcesOnChange:
    YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.REFETCHES_RESOURCES_ON_CHANGE,
  reconcileValueWithOptions:
    YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.RECONCILE_VALUE_WITH_OPTIONS,
  derivedFieldsSyncOnChange:
    YUP.ROLES_AND_POLICIES.INSTALLER_ROLE_ARN_SCHEMA.META.DERIVED_FIELDS_SYNC_ON_CHANGE,
} satisfies WizardFieldMeta);

export const supportRoleArnSchema = rosaRequiredStringField().meta({
  id: YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.ID,
  labelKey: YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.LABEL_KEY,
  labelHelpKey: YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.LABEL_HELP_KEY,
  placeholderKey: YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.PLACEHOLDER_KEY,
  stepId: YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.STEP_ID,
  fieldType: YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.FIELD_TYPE,
  noEditAfterSubmit: YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.NO_EDIT_AFTER_SUBMIT,
  optionsWizardDataResource:
    YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.OPTIONS_WIZARD_DATA_RESOURCE,
  reconcileValueWithOptions:
    YUP.ROLES_AND_POLICIES.SUPPORT_ROLE_ARN_SCHEMA.META.RECONCILE_VALUE_WITH_OPTIONS,
} satisfies WizardFieldMeta);

export const workerRoleArnSchema = rosaRequiredStringField().meta({
  id: YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.ID,
  labelKey: YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.LABEL_KEY,
  labelHelpKey: YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.LABEL_HELP_KEY,
  placeholderKey: YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.PLACEHOLDER_KEY,
  stepId: YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.STEP_ID,
  fieldType: YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.FIELD_TYPE,
  noEditAfterSubmit: YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.NO_EDIT_AFTER_SUBMIT,
  optionsWizardDataResource:
    YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.OPTIONS_WIZARD_DATA_RESOURCE,
  reconcileValueWithOptions:
    YUP.ROLES_AND_POLICIES.WORKER_ROLE_ARN_SCHEMA.META.RECONCILE_VALUE_WITH_OPTIONS,
} satisfies WizardFieldMeta);

export const byoOidcConfigIdSchema = rosaRequiredStringField().meta({
  id: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.ID,
  labelKey: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.LABEL_KEY,
  labelHelpKey: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.LABEL_HELP_KEY,
  placeholderKey: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.PLACEHOLDER_KEY,
  labelHelpTitleKey: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.LABEL_HELP_TITLE_KEY,
  stepId: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.STEP_ID,
  fieldType: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.FIELD_TYPE,
  noEditAfterSubmit: YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.NO_EDIT_AFTER_SUBMIT,
  optionsWizardDataResource:
    YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.OPTIONS_WIZARD_DATA_RESOURCE,
  reconcileValueWithOptions:
    YUP.ROLES_AND_POLICIES.BYO_OIDC_CONFIG_ID_SCHEMA.META.RECONCILE_VALUE_WITH_OPTIONS,
} satisfies WizardFieldMeta);

export const customOperatorRolesPrefixSchema = rosaRequiredStringField()
  .default(YUP.ROLES_AND_POLICIES.CUSTOM_OPERATOR_ROLES_PREFIX_SCHEMA.DEFAULT)
  .meta({
    id: YUP.ROLES_AND_POLICIES.CUSTOM_OPERATOR_ROLES_PREFIX_SCHEMA.META.ID,
    labelKey: YUP.ROLES_AND_POLICIES.CUSTOM_OPERATOR_ROLES_PREFIX_SCHEMA.META.LABEL_KEY,
    stepId: YUP.ROLES_AND_POLICIES.CUSTOM_OPERATOR_ROLES_PREFIX_SCHEMA.META.STEP_ID,
    fieldType: YUP.ROLES_AND_POLICIES.CUSTOM_OPERATOR_ROLES_PREFIX_SCHEMA.META.FIELD_TYPE,
    noEditAfterSubmit:
      YUP.ROLES_AND_POLICIES.CUSTOM_OPERATOR_ROLES_PREFIX_SCHEMA.META.NO_EDIT_AFTER_SUBMIT,
  } satisfies WizardFieldMeta)
  .test(FIELD_NAME.CUSTOM_OPERATOR_ROLES_PREFIX, '', function (value) {
    if (!value) return true;
    const { msgs } = ctx(this);
    const label = msgs.operatorRolesPrefix.fieldLabel;
    if (!DNS_LABEL_REGEXP.test(value)) {
      return this.createError({ message: msgs.operatorRolesPrefix.invalidFormat(label, value) });
    }
    if (value.length > MAX_CUSTOM_OPERATOR_ROLES_PREFIX_LENGTH) {
      return this.createError({
        message: msgs.operatorRolesPrefix.tooLong(label, MAX_CUSTOM_OPERATOR_ROLES_PREFIX_LENGTH),
      });
    }
    return true;
  });

export const rolesAndPoliciesFields = {
  installer_role_arn: installerRoleArnSchema,
  support_role_arn: supportRoleArnSchema,
  worker_role_arn: workerRoleArnSchema,
  byo_oidc_config_id: byoOidcConfigIdSchema,
  custom_operator_roles_prefix: customOperatorRolesPrefixSchema,
};
